services:
  app:
    build: .
    restart: always
    container_name: SpringBootDataBaseMongoDB-APP
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - ./.env
    depends_on:
      - mongo-express

  mongo:
    image: mongo
    restart: always
    container_name: SpringBootDataBaseMongoDB-MongoDB
    ports:
      - ${MONGO_DB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    container_name: SpringBootDataBaseMongoDB-MongoExpress
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false